spring:
  datasource:
    url: jdbc:mysql://your.prod.db:3306/lol_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
